singleQuote: false
trailingComma: "all"
printWidth: 100
tabWidth: 4
useTabs: false
quoteProps: as-needed
overrides:
  - files: "package.json"
    options:
      parser: json
  - files: "mock/*.ts"
    options:
      trailingComma: none
      quoteProps: preserve
